name: coin_flutter
description: A very coiny flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.5
  rxdart: ^0.27.7
  get_it: ^7.6.7
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  test: ^1.24.9

flutter:
  uses-material-design: true
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
